version: '3.8'

services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
    container_name: laravel-container
    working_dir: /var/www/html/Practical-docker/backend
    volumes:
      - /var/www/html/Practical-docker/backend
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_DATABASE=practical-demo
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
    container_name: react-container
    working_dir: /var/www/html/Practical-docker/frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0.24
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practical-demo
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge